import org.slf4j.LoggerFactory
import com.yubraj.drools.App
import com.yubraj.drools.model.Product
import com.yubraj.drools.enums.TypeEnum

import function com.yubraj.drools.utils.SomeUtil.replaceAWithB
import function org.drools.core.util.StringUtils.isEmpty


rule "MEDICAL rule"
 dialect "mvel"
when
     $product : Product( typeEnum == TypeEnum.MEDICAL, productName != replaceAWithB($product.typeEnum.someOutputString) )
then
     modify ($product) {productName = replaceAWithB($product.typeEnum.someOutputString)}
     LoggerFactory.getLogger(DroolsSpring.class).debug(String.format("MEDICAL rule applied, product name is now equal to [%s]", $product.productName))
end

rule "ELECTRONIC rule"
 dialect "mvel"
when
     $product : Product( typeEnum == TypeEnum.ELECTRONIC, productName != replaceAWithB($product.typeEnum.someOutputString) )
then
     modify ($product) {productName = replaceAWithB($product.typeEnum.someOutputString)}
     LoggerFactory.getLogger(DroolsSpring.class).debug(String.format("ELECTRONIC rule applied, product name is now equal to [%s]", $product.productName))
end